"""Threshold and grouping constants for concern generation."""

from __future__ import annotations

from desloppify.engine.detectors.base import (
    ELEVATED_LOC_THRESHOLD,
    ELEVATED_NESTING_THRESHOLD,
    ELEVATED_PARAMS_THRESHOLD,
)

ELEVATED_MAX_PARAMS = ELEVATED_PARAMS_THRESHOLD
ELEVATED_MAX_NESTING = ELEVATED_NESTING_THRESHOLD
ELEVATED_LOC = ELEVATED_LOC_THRESHOLD
MIN_DETECTORS_FOR_MIXED = 3
MIN_FILES_FOR_SYSTEMIC = 3
MIN_FILES_FOR_SMELL_PATTERN = 5

__all__ = [
    "ELEVATED_LOC",
    "ELEVATED_MAX_NESTING",
    "ELEVATED_MAX_PARAMS",
    "MIN_DETECTORS_FOR_MIXED",
    "MIN_FILES_FOR_SMELL_PATTERN",
    "MIN_FILES_FOR_SYSTEMIC",
]
