"""Detector catalog constants used by the runtime registry."""

from __future__ import annotations

from dataclasses import dataclass

DISPLAY_ORDER = [
    "logs",
    "unused",
    "exports",
    "deprecated",
    "structural",
    "props",
    "single_use",
    "coupling",
    "cycles",
    "orphaned",
    "uncalled_functions",
    "unused_enums",
    "facade",
    "patterns",
    "naming",
    "smells",
    "react",
    "dupes",
    "stale_exclude",
    "dict_keys",
    "flat_dirs",
    "signature",
    "global_mutable_config",
    "private_imports",
    "layer_violation",
    "test_coverage",
    "security",
    "concerns",
    "review",
    "subjective_review",
]


@dataclass(frozen=True)
class DetectorMeta:
    name: str
    display: str  # Human-readable for terminal display
    dimension: str  # Scoring dimension name
    action_type: str  # "auto_fix" | "refactor" | "reorganize" | "manual_fix"
    guidance: str  # Narrative coaching text
    fixers: tuple[str, ...] = ()
    tool: str = ""  # "move" or empty
    structural: bool = False  # Merges under "structural" in display
    needs_judgment: bool = False  # Issues need LLM design judgment (vs clear-cut fixes)
    standalone_threshold: str | None = None  # Min confidence for standalone queue item
    tier: int = 2  # T1-T4 scoring weight
    marks_dims_stale: bool = False  # Mechanical changes should stale subjective dimensions


DETECTORS: dict[str, DetectorMeta] = {
    # ── Auto-fixable ──────────────────────────────────────
    "unused": DetectorMeta(
        "unused",
        "unused",
        "Code quality",
        "auto_fix",
        "remove unused imports and variables",
        fixers=("unused-imports", "unused-vars", "unused-params"),
        tier=3,
    ),
    "logs": DetectorMeta(
        "logs",
        "logs",
        "Code quality",
        "auto_fix",
        "remove debug logs",
        fixers=("debug-logs",),
        tier=3,
    ),
    "exports": DetectorMeta(
        "exports",
        "exports",
        "Code quality",
        "manual_fix",
        "run `knip --fix` to remove dead exports",
        tier=3,
    ),
    "smells": DetectorMeta(
        "smells",
        "smells",
        "Code quality",
        "auto_fix",
        "fix code smells — dead useEffect, empty if chains",
        fixers=("dead-useeffect", "empty-if-chain"),
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    # ── Reorganize (move tool) ────────────────────────────
    "orphaned": DetectorMeta(
        "orphaned",
        "orphaned",
        "Code quality",
        "reorganize",
        "delete dead files or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "uncalled_functions": DetectorMeta(
        "uncalled_functions",
        "uncalled functions",
        "Code quality",
        "refactor",
        "remove dead functions or document why they're retained",
        needs_judgment=True,
        marks_dims_stale=True,
    ),
    "unused_enums": DetectorMeta(
        "unused_enums",
        "unused enums",
        "unused",
        "manual_fix",
        "remove unused enum classes or add imports where they belong",
    ),
    "flat_dirs": DetectorMeta(
        "flat_dirs",
        "flat dirs",
        "Code quality",
        "reorganize",
        "create subdirectories and use `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "naming": DetectorMeta(
        "naming",
        "naming",
        "Code quality",
        "reorganize",
        "rename files with `desloppify move` to fix conventions",
        tool="move",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    "single_use": DetectorMeta(
        "single_use",
        "single_use",
        "Code quality",
        "reorganize",
        "inline or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
    ),
    "coupling": DetectorMeta(
        "coupling",
        "coupling",
        "Code quality",
        "reorganize",
        "fix boundary violations with `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "cycles": DetectorMeta(
        "cycles",
        "cycles",
        "Security",
        "reorganize",
        "break cycles by extracting shared code or using `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=4,
        marks_dims_stale=True,
    ),
    "facade": DetectorMeta(
        "facade",
        "facade",
        "Code quality",
        "reorganize",
        "flatten re-export facades or consolidate barrel files",
        tool="move",
        needs_judgment=True,
        tier=3,
    ),
    # ── Refactor ──────────────────────────────────────────
    "structural": DetectorMeta(
        "structural",
        "structural",
        "File health",
        "refactor",
        "review large files — split only when responsibilities are clearly separable",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "props": DetectorMeta(
        "props",
        "props",
        "Code quality",
        "refactor",
        "split bloated components, extract sub-components",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "react": DetectorMeta(
        "react",
        "react",
        "Code quality",
        "refactor",
        "refactor React antipatterns (state sync, provider nesting, hook bloat)",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "dupes": DetectorMeta(
        "dupes",
        "dupes",
        "Duplication",
        "refactor",
        "extract shared utility or consolidate duplicates",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    "patterns": DetectorMeta(
        "patterns",
        "patterns",
        "Code quality",
        "refactor",
        "align to single pattern across the codebase",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "dict_keys": DetectorMeta(
        "dict_keys",
        "dict keys",
        "Code quality",
        "refactor",
        "fix dict key mismatches — dead writes are likely dead code, "
        "schema drift suggests a typo or missed rename",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "test_coverage": DetectorMeta(
        "test_coverage",
        "test coverage",
        "Test health",
        "refactor",
        "add tests for untested production modules — prioritize by import count",
        tier=4,
    ),
    "signature": DetectorMeta(
        "signature",
        "signature",
        "Code quality",
        "refactor",
        "consolidate inconsistent function signatures",
        needs_judgment=True,
    ),
    "global_mutable_config": DetectorMeta(
        "global_mutable_config",
        "global mutable config",
        "Code quality",
        "manual_fix",
        "refactor module-level mutable state — use explicit init functions or dependency injection",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "private_imports": DetectorMeta(
        "private_imports",
        "private imports",
        "Code quality",
        "manual_fix",
        "stop importing private symbols across module boundaries",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "layer_violation": DetectorMeta(
        "layer_violation",
        "layer violation",
        "Code quality",
        "manual_fix",
        "fix architectural layer violations — move shared code to the correct layer",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "responsibility_cohesion": DetectorMeta(
        "responsibility_cohesion",
        "responsibility cohesion",
        "Code quality",
        "refactor",
        "split modules with too many responsibilities — extract focused sub-modules",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "boilerplate_duplication": DetectorMeta(
        "boilerplate_duplication",
        "boilerplate duplication",
        "Duplication",
        "refactor",
        "extract shared boilerplate into reusable helpers or base classes",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "stale_wontfix": DetectorMeta(
        "stale_wontfix",
        "stale wontfix",
        "Code quality",
        "manual_fix",
        "re-evaluate old wontfix decisions — fix, document, or escalate",
    ),
    "concerns": DetectorMeta(
        "concerns",
        "design concerns",
        "Design coherence",
        "refactor",
        "address design concerns confirmed by subjective evaluation",
    ),
    # ── Manual fix ────────────────────────────────────────
    "deprecated": DetectorMeta(
        "deprecated",
        "deprecated",
        "Code quality",
        "manual_fix",
        "remove deprecated symbols or migrate callers",
        tier=3,
    ),
    "stale_exclude": DetectorMeta(
        "stale_exclude",
        "stale exclude",
        "Code quality",
        "manual_fix",
        "remove stale exclusion or verify it's still needed",
        tier=3,
    ),
    "security": DetectorMeta(
        "security",
        "security",
        "Security",
        "manual_fix",
        "review and fix security issues — prioritize by severity",
        tier=4,
    ),
    # ── Subjective review ────────────────────────────────────
    "review": DetectorMeta(
        "review",
        "design review",
        "Test health",
        "refactor",
        "address design quality issues from AI code review",
    ),
    "subjective_review": DetectorMeta(
        "subjective_review",
        "subjective review",
        "Test health",
        "manual_fix",
        "run `desloppify review --prepare` to evaluate files against quality dimensions",
        tier=4,
    ),
}

